project:
  type: website
  output-dir: docs

website:
  title: "Wyatt Erickson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - project.qmd
      - freeforall.qmd
      - resume.qmd
    right: 
      - icon: github
        href: https://github.com/werickson13
      - icon: envelope
        href: mailto:wyatterickson@ucsb.edu

format:
  html:
    theme: 
      - sandstone
      - docs/styles.scss #removed styles.css, using scss instead
    toc: true
    page-layout: full

editor: visual

